Save documentation upon tagging a release

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -55,3 +55,42 @@ jobs:
           body_path: ${{ github.workflow }}-CHANGELOG.txt
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Install Dependencies
+        run: |
+          poetry run pip3 install "vtk==8.1.2"
+          poetry run pip3 install numpy
+          poetry run pip3 install mayavi
+          poetry install -E full
+          poetry run pip3 install "vtk==8.1.2"
+        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
+
+      - name: Produce documentation
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y pandoc
+          sudo apt-get install -y xvfb
+          cd docs/
+          xvfb-run poetry run make html
+          cd ..
+
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/sbozzolo/kuibit.git --branch gh-pages --single-branch gh-pages
+          mkdir -p gh-pages/"$(poetry version -s)"
+          cp -r docs/_build/html/* gh-pages/"$(poetry version -s)"
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          # force: true
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
